# .github/workflows/ci.yml
name: CI – Lint & Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  backend:
    name: Laravel Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports: ['3306:3306']
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: pdo, pdo_mysql
      - name: Install dependencies
        run: |
          cd server
          composer install
          cp .env.example .env
          php artisan key:generate
      - name: Run tests
        run: |
          cd server
          php artisan migrate --env=testing --force
          php artisan test

  frontend:
    name: Frontend Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      - name: Lint and Type Check
        run: |
          cd frontend
          npm run lint
          npm run type-check
